// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/apps/vpn/proto/vpn.proto

package vpn

import (
	common "biz-auto-api/pkg/grpc/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRes) Reset() {
	*x = PingRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRes) ProtoMessage() {}

func (x *PingRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRes.ProtoReflect.Descriptor instead.
func (*PingRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{0}
}

func (x *PingRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetSwitchIfBusinessReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	// @gotags: validate:"required,min=0,max=65536"
	Port int64 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty" validate:"required,min=0,max=65536"`
	// @gotags: validate:"required"
	Community string `protobuf:"bytes,3,opt,name=community,proto3" json:"community,omitempty" validate:"required"`
	// @gotags: validate:"required,min=0,max=60"
	Timeout int64 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty" validate:"required,min=0,max=60"`
	// @gotags: validate:"required,min=1,max=5"
	Retry         int64 `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty" validate:"required,min=1,max=5"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwitchIfBusinessReq) Reset() {
	*x = GetSwitchIfBusinessReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwitchIfBusinessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwitchIfBusinessReq) ProtoMessage() {}

func (x *GetSwitchIfBusinessReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwitchIfBusinessReq.ProtoReflect.Descriptor instead.
func (*GetSwitchIfBusinessReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{1}
}

func (x *GetSwitchIfBusinessReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetSwitchIfBusinessReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GetSwitchIfBusinessReq) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *GetSwitchIfBusinessReq) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *GetSwitchIfBusinessReq) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

type GetSwitchIfBusinessRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Business      []string               `protobuf:"bytes,1,rep,name=business,proto3" json:"business,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwitchIfBusinessRes) Reset() {
	*x = GetSwitchIfBusinessRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwitchIfBusinessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwitchIfBusinessRes) ProtoMessage() {}

func (x *GetSwitchIfBusinessRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwitchIfBusinessRes.ProtoReflect.Descriptor instead.
func (*GetSwitchIfBusinessRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{2}
}

func (x *GetSwitchIfBusinessRes) GetBusiness() []string {
	if x != nil {
		return x.Business
	}
	return nil
}

type CollectSwitchTrafficReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	// @gotags: validate:"required,min=0,max=65536"
	Port int64 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty" validate:"required,min=0,max=65536"`
	// @gotags: validate:"required"
	Community string `protobuf:"bytes,3,opt,name=community,proto3" json:"community,omitempty" validate:"required"`
	// @gotags: validate:"required,min=0,max=60"
	Timeout int64 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty" validate:"required,min=0,max=60"`
	// @gotags: validate:"required,min=1,max=5"
	Retry int64 `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty" validate:"required,min=1,max=5"`
	// @gotags: validate:"required,min=1"
	CollectInterval int64 `protobuf:"varint,6,opt,name=collectInterval,proto3" json:"collectInterval,omitempty" validate:"required,min=1"`
	// @gotags: validate:"required,min=1"
	CollectTimes  int64 `protobuf:"varint,7,opt,name=collectTimes,proto3" json:"collectTimes,omitempty" validate:"required,min=1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSwitchTrafficReq) Reset() {
	*x = CollectSwitchTrafficReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSwitchTrafficReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSwitchTrafficReq) ProtoMessage() {}

func (x *CollectSwitchTrafficReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSwitchTrafficReq.ProtoReflect.Descriptor instead.
func (*CollectSwitchTrafficReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{3}
}

func (x *CollectSwitchTrafficReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CollectSwitchTrafficReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CollectSwitchTrafficReq) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *CollectSwitchTrafficReq) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CollectSwitchTrafficReq) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *CollectSwitchTrafficReq) GetCollectInterval() int64 {
	if x != nil {
		return x.CollectInterval
	}
	return 0
}

func (x *CollectSwitchTrafficReq) GetCollectTimes() int64 {
	if x != nil {
		return x.CollectTimes
	}
	return 0
}

type CollectSwitchTrafficItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	IsUplink      bool                   `protobuf:"varint,5,opt,name=isUplink,proto3" json:"isUplink,omitempty"`
	IsDownlink    bool                   `protobuf:"varint,6,opt,name=isDownlink,proto3" json:"isDownlink,omitempty"`
	IsSpeedLimit  bool                   `protobuf:"varint,7,opt,name=isSpeedLimit,proto3" json:"isSpeedLimit,omitempty"`
	PeakBusiness  string                 `protobuf:"bytes,8,opt,name=peakBusiness,proto3" json:"peakBusiness,omitempty"`
	Alias         string                 `protobuf:"bytes,9,opt,name=alias,proto3" json:"alias,omitempty"`
	Speed         *IfTrafficSpeed        `protobuf:"bytes,10,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSwitchTrafficItem) Reset() {
	*x = CollectSwitchTrafficItem{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSwitchTrafficItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSwitchTrafficItem) ProtoMessage() {}

func (x *CollectSwitchTrafficItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSwitchTrafficItem.ProtoReflect.Descriptor instead.
func (*CollectSwitchTrafficItem) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{4}
}

func (x *CollectSwitchTrafficItem) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CollectSwitchTrafficItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectSwitchTrafficItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CollectSwitchTrafficItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CollectSwitchTrafficItem) GetIsUplink() bool {
	if x != nil {
		return x.IsUplink
	}
	return false
}

func (x *CollectSwitchTrafficItem) GetIsDownlink() bool {
	if x != nil {
		return x.IsDownlink
	}
	return false
}

func (x *CollectSwitchTrafficItem) GetIsSpeedLimit() bool {
	if x != nil {
		return x.IsSpeedLimit
	}
	return false
}

func (x *CollectSwitchTrafficItem) GetPeakBusiness() string {
	if x != nil {
		return x.PeakBusiness
	}
	return ""
}

func (x *CollectSwitchTrafficItem) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *CollectSwitchTrafficItem) GetSpeed() *IfTrafficSpeed {
	if x != nil {
		return x.Speed
	}
	return nil
}

type CollectSwitchTrafficRes struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*CollectSwitchTrafficItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSwitchTrafficRes) Reset() {
	*x = CollectSwitchTrafficRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSwitchTrafficRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSwitchTrafficRes) ProtoMessage() {}

func (x *CollectSwitchTrafficRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSwitchTrafficRes.ProtoReflect.Descriptor instead.
func (*CollectSwitchTrafficRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{5}
}

func (x *CollectSwitchTrafficRes) GetItems() []*CollectSwitchTrafficItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type IfTrafficSpeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	Index         int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Inbps         float64                `protobuf:"fixed64,3,opt,name=inbps,proto3" json:"inbps,omitempty"`
	Outbps        float64                `protobuf:"fixed64,4,opt,name=outbps,proto3" json:"outbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfTrafficSpeed) Reset() {
	*x = IfTrafficSpeed{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfTrafficSpeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfTrafficSpeed) ProtoMessage() {}

func (x *IfTrafficSpeed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfTrafficSpeed.ProtoReflect.Descriptor instead.
func (*IfTrafficSpeed) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{6}
}

func (x *IfTrafficSpeed) GetT() *timestamppb.Timestamp {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *IfTrafficSpeed) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *IfTrafficSpeed) GetInbps() float64 {
	if x != nil {
		return x.Inbps
	}
	return 0
}

func (x *IfTrafficSpeed) GetOutbps() float64 {
	if x != nil {
		return x.Outbps
	}
	return 0
}

type GetIfInLimitConfReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target        string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	Port          int64  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKey    string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIfInLimitConfReq) Reset() {
	*x = GetIfInLimitConfReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIfInLimitConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIfInLimitConfReq) ProtoMessage() {}

func (x *GetIfInLimitConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIfInLimitConfReq.ProtoReflect.Descriptor instead.
func (*GetIfInLimitConfReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{7}
}

func (x *GetIfInLimitConfReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetIfInLimitConfReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GetIfInLimitConfReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetIfInLimitConfReq) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type IfLimitConfItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	QosInTemplateName string                 `protobuf:"bytes,2,opt,name=qosInTemplateName,proto3" json:"qosInTemplateName,omitempty"`
	QosInTemplate     *QosInTemplate         `protobuf:"bytes,3,opt,name=qosInTemplate,proto3" json:"qosInTemplate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IfLimitConfItem) Reset() {
	*x = IfLimitConfItem{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfLimitConfItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfLimitConfItem) ProtoMessage() {}

func (x *IfLimitConfItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfLimitConfItem.ProtoReflect.Descriptor instead.
func (*IfLimitConfItem) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{8}
}

func (x *IfLimitConfItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IfLimitConfItem) GetQosInTemplateName() string {
	if x != nil {
		return x.QosInTemplateName
	}
	return ""
}

func (x *IfLimitConfItem) GetQosInTemplate() *QosInTemplate {
	if x != nil {
		return x.QosInTemplate
	}
	return nil
}

type QosInTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ratebps       int64                  `protobuf:"varint,2,opt,name=ratebps,proto3" json:"ratebps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QosInTemplate) Reset() {
	*x = QosInTemplate{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosInTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosInTemplate) ProtoMessage() {}

func (x *QosInTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosInTemplate.ProtoReflect.Descriptor instead.
func (*QosInTemplate) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{9}
}

func (x *QosInTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QosInTemplate) GetRatebps() int64 {
	if x != nil {
		return x.Ratebps
	}
	return 0
}

type GetIfInLimitConfRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*IfLimitConfItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIfInLimitConfRes) Reset() {
	*x = GetIfInLimitConfRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIfInLimitConfRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIfInLimitConfRes) ProtoMessage() {}

func (x *GetIfInLimitConfRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIfInLimitConfRes.ProtoReflect.Descriptor instead.
func (*GetIfInLimitConfRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{10}
}

func (x *GetIfInLimitConfRes) GetItems() []*IfLimitConfItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type IfLimitReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target     string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	Port       int64  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username   string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKey string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	// @gotags: validate:"required,gt=0"
	LimitValue int64 `protobuf:"varint,5,opt,name=limitValue,proto3" json:"limitValue,omitempty" validate:"required,gt=0"`
	// @gotags: validate:"required"
	IfName        string `protobuf:"bytes,6,opt,name=ifName,proto3" json:"ifName,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfLimitReq) Reset() {
	*x = IfLimitReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfLimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfLimitReq) ProtoMessage() {}

func (x *IfLimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfLimitReq.ProtoReflect.Descriptor instead.
func (*IfLimitReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{11}
}

func (x *IfLimitReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *IfLimitReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *IfLimitReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IfLimitReq) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *IfLimitReq) GetLimitValue() int64 {
	if x != nil {
		return x.LimitValue
	}
	return 0
}

func (x *IfLimitReq) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

type IfLimitRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsoleLog    string                 `protobuf:"bytes,1,opt,name=consoleLog,proto3" json:"consoleLog,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfLimitRes) Reset() {
	*x = IfLimitRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfLimitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfLimitRes) ProtoMessage() {}

func (x *IfLimitRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfLimitRes.ProtoReflect.Descriptor instead.
func (*IfLimitRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{12}
}

func (x *IfLimitRes) GetConsoleLog() string {
	if x != nil {
		return x.ConsoleLog
	}
	return ""
}

func (x *IfLimitRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IfLimitRes) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type IfUnlimitReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target     string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	Port       int64  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username   string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKey string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	// @gotags: validate:"required"
	IfName        string `protobuf:"bytes,5,opt,name=ifName,proto3" json:"ifName,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfUnlimitReq) Reset() {
	*x = IfUnlimitReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfUnlimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfUnlimitReq) ProtoMessage() {}

func (x *IfUnlimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfUnlimitReq.ProtoReflect.Descriptor instead.
func (*IfUnlimitReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{13}
}

func (x *IfUnlimitReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *IfUnlimitReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *IfUnlimitReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IfUnlimitReq) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *IfUnlimitReq) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

type IfUnlimitRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsoleLog    string                 `protobuf:"bytes,1,opt,name=consoleLog,proto3" json:"consoleLog,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfUnlimitRes) Reset() {
	*x = IfUnlimitRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfUnlimitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfUnlimitRes) ProtoMessage() {}

func (x *IfUnlimitRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfUnlimitRes.ProtoReflect.Descriptor instead.
func (*IfUnlimitRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{14}
}

func (x *IfUnlimitRes) GetConsoleLog() string {
	if x != nil {
		return x.ConsoleLog
	}
	return ""
}

func (x *IfUnlimitRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IfUnlimitRes) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetIfBaseInfoReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	// @gotags: validate:"required,min=0,max=65536"
	Port int64 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty" validate:"required,min=0,max=65536"`
	// @gotags: validate:"required"
	Community string `protobuf:"bytes,3,opt,name=community,proto3" json:"community,omitempty" validate:"required"`
	// @gotags: validate:"required,min=0,max=60"
	Timeout int64 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty" validate:"required,min=0,max=60"`
	// @gotags: validate:"required,min=1,max=5"
	Retry         int64 `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty" validate:"required,min=1,max=5"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIfBaseInfoReq) Reset() {
	*x = GetIfBaseInfoReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIfBaseInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIfBaseInfoReq) ProtoMessage() {}

func (x *GetIfBaseInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIfBaseInfoReq.ProtoReflect.Descriptor instead.
func (*GetIfBaseInfoReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{15}
}

func (x *GetIfBaseInfoReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetIfBaseInfoReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GetIfBaseInfoReq) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *GetIfBaseInfoReq) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *GetIfBaseInfoReq) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

type IfBaseInfoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	IsUplink      bool                   `protobuf:"varint,5,opt,name=isUplink,proto3" json:"isUplink,omitempty"`
	IsDownlink    bool                   `protobuf:"varint,6,opt,name=isDownlink,proto3" json:"isDownlink,omitempty"`
	IsSpeedLimit  bool                   `protobuf:"varint,7,opt,name=isSpeedLimit,proto3" json:"isSpeedLimit,omitempty"`
	PeakBusiness  string                 `protobuf:"bytes,8,opt,name=peakBusiness,proto3" json:"peakBusiness,omitempty"`
	Alias         string                 `protobuf:"bytes,9,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfBaseInfoItem) Reset() {
	*x = IfBaseInfoItem{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfBaseInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfBaseInfoItem) ProtoMessage() {}

func (x *IfBaseInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfBaseInfoItem.ProtoReflect.Descriptor instead.
func (*IfBaseInfoItem) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{16}
}

func (x *IfBaseInfoItem) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *IfBaseInfoItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IfBaseInfoItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IfBaseInfoItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IfBaseInfoItem) GetIsUplink() bool {
	if x != nil {
		return x.IsUplink
	}
	return false
}

func (x *IfBaseInfoItem) GetIsDownlink() bool {
	if x != nil {
		return x.IsDownlink
	}
	return false
}

func (x *IfBaseInfoItem) GetIsSpeedLimit() bool {
	if x != nil {
		return x.IsSpeedLimit
	}
	return false
}

func (x *IfBaseInfoItem) GetPeakBusiness() string {
	if x != nil {
		return x.PeakBusiness
	}
	return ""
}

func (x *IfBaseInfoItem) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type GetIfBaseInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*IfBaseInfoItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIfBaseInfoRes) Reset() {
	*x = GetIfBaseInfoRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIfBaseInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIfBaseInfoRes) ProtoMessage() {}

func (x *GetIfBaseInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIfBaseInfoRes.ProtoReflect.Descriptor instead.
func (*GetIfBaseInfoRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{17}
}

func (x *GetIfBaseInfoRes) GetItems() []*IfBaseInfoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetIfTrafficCounterReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	// @gotags: validate:"required,min=0,max=65536"
	Port int64 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty" validate:"required,min=0,max=65536"`
	// @gotags: validate:"required"
	Community string `protobuf:"bytes,3,opt,name=community,proto3" json:"community,omitempty" validate:"required"`
	// @gotags: validate:"required,min=0,max=60"
	Timeout int64 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty" validate:"required,min=0,max=60"`
	// @gotags: validate:"required,min=1,max=5"
	Retry         int64 `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty" validate:"required,min=1,max=5"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIfTrafficCounterReq) Reset() {
	*x = GetIfTrafficCounterReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIfTrafficCounterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIfTrafficCounterReq) ProtoMessage() {}

func (x *GetIfTrafficCounterReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIfTrafficCounterReq.ProtoReflect.Descriptor instead.
func (*GetIfTrafficCounterReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{18}
}

func (x *GetIfTrafficCounterReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetIfTrafficCounterReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GetIfTrafficCounterReq) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *GetIfTrafficCounterReq) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *GetIfTrafficCounterReq) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

type IfTrafficCounterItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InTime        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=inTime,proto3" json:"inTime,omitempty"`
	OutTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=outTime,proto3" json:"outTime,omitempty"`
	Index         int64                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	InByte        uint64                 `protobuf:"varint,4,opt,name=inByte,proto3" json:"inByte,omitempty"`
	OutByte       uint64                 `protobuf:"varint,5,opt,name=outByte,proto3" json:"outByte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfTrafficCounterItem) Reset() {
	*x = IfTrafficCounterItem{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfTrafficCounterItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfTrafficCounterItem) ProtoMessage() {}

func (x *IfTrafficCounterItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfTrafficCounterItem.ProtoReflect.Descriptor instead.
func (*IfTrafficCounterItem) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{19}
}

func (x *IfTrafficCounterItem) GetInTime() *timestamppb.Timestamp {
	if x != nil {
		return x.InTime
	}
	return nil
}

func (x *IfTrafficCounterItem) GetOutTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OutTime
	}
	return nil
}

func (x *IfTrafficCounterItem) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *IfTrafficCounterItem) GetInByte() uint64 {
	if x != nil {
		return x.InByte
	}
	return 0
}

func (x *IfTrafficCounterItem) GetOutByte() uint64 {
	if x != nil {
		return x.OutByte
	}
	return 0
}

type GetIfTrafficCounterRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*IfTrafficCounterItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIfTrafficCounterRes) Reset() {
	*x = GetIfTrafficCounterRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIfTrafficCounterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIfTrafficCounterRes) ProtoMessage() {}

func (x *GetIfTrafficCounterRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIfTrafficCounterRes.ProtoReflect.Descriptor instead.
func (*GetIfTrafficCounterRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{20}
}

func (x *GetIfTrafficCounterRes) GetItems() []*IfTrafficCounterItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type IfRangeLimitReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target     string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	Port       int64  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username   string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKey string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	// @gotags: validate:"required,gt=0"
	LimitValue int64 `protobuf:"varint,5,opt,name=limitValue,proto3" json:"limitValue,omitempty" validate:"required,gt=0"`
	// @gotags: validate:"required"
	IfNameRange   string `protobuf:"bytes,6,opt,name=ifNameRange,proto3" json:"ifNameRange,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfRangeLimitReq) Reset() {
	*x = IfRangeLimitReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfRangeLimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfRangeLimitReq) ProtoMessage() {}

func (x *IfRangeLimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfRangeLimitReq.ProtoReflect.Descriptor instead.
func (*IfRangeLimitReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{21}
}

func (x *IfRangeLimitReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *IfRangeLimitReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *IfRangeLimitReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IfRangeLimitReq) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *IfRangeLimitReq) GetLimitValue() int64 {
	if x != nil {
		return x.LimitValue
	}
	return 0
}

func (x *IfRangeLimitReq) GetIfNameRange() string {
	if x != nil {
		return x.IfNameRange
	}
	return ""
}

type IfRangeLimitRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsoleLog    string                 `protobuf:"bytes,1,opt,name=consoleLog,proto3" json:"consoleLog,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfRangeLimitRes) Reset() {
	*x = IfRangeLimitRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfRangeLimitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfRangeLimitRes) ProtoMessage() {}

func (x *IfRangeLimitRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfRangeLimitRes.ProtoReflect.Descriptor instead.
func (*IfRangeLimitRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{22}
}

func (x *IfRangeLimitRes) GetConsoleLog() string {
	if x != nil {
		return x.ConsoleLog
	}
	return ""
}

func (x *IfRangeLimitRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IfRangeLimitRes) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type IfRangeUnlimitReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required"
	Target     string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty" validate:"required"`
	Port       int64  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username   string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKey string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	// @gotags: validate:"required"
	IfNameRange   string `protobuf:"bytes,5,opt,name=ifNameRange,proto3" json:"ifNameRange,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfRangeUnlimitReq) Reset() {
	*x = IfRangeUnlimitReq{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfRangeUnlimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfRangeUnlimitReq) ProtoMessage() {}

func (x *IfRangeUnlimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfRangeUnlimitReq.ProtoReflect.Descriptor instead.
func (*IfRangeUnlimitReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{23}
}

func (x *IfRangeUnlimitReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *IfRangeUnlimitReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *IfRangeUnlimitReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IfRangeUnlimitReq) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *IfRangeUnlimitReq) GetIfNameRange() string {
	if x != nil {
		return x.IfNameRange
	}
	return ""
}

type IfRangeUnlimitRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsoleLog    string                 `protobuf:"bytes,1,opt,name=consoleLog,proto3" json:"consoleLog,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfRangeUnlimitRes) Reset() {
	*x = IfRangeUnlimitRes{}
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfRangeUnlimitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfRangeUnlimitRes) ProtoMessage() {}

func (x *IfRangeUnlimitRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_vpn_proto_vpn_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfRangeUnlimitRes.ProtoReflect.Descriptor instead.
func (*IfRangeUnlimitRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP(), []int{24}
}

func (x *IfRangeUnlimitRes) GetConsoleLog() string {
	if x != nil {
		return x.ConsoleLog
	}
	return ""
}

func (x *IfRangeUnlimitRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IfRangeUnlimitRes) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_internal_apps_vpn_proto_vpn_proto protoreflect.FileDescriptor

const file_internal_apps_vpn_proto_vpn_proto_rawDesc = "" +
	"\n" +
	"!internal/apps/vpn/proto/vpn.proto\x12\x03vpn\x1a\x1bpkg/grpc/proto/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n" +
	"\aPingRes\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x92\x01\n" +
	"\x16GetSwitchIfBusinessReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1c\n" +
	"\tcommunity\x18\x03 \x01(\tR\tcommunity\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x03R\x05retry\"4\n" +
	"\x16GetSwitchIfBusinessRes\x12\x1a\n" +
	"\bbusiness\x18\x01 \x03(\tR\bbusiness\"\xe1\x01\n" +
	"\x17CollectSwitchTrafficReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1c\n" +
	"\tcommunity\x18\x03 \x01(\tR\tcommunity\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x03R\x05retry\x12(\n" +
	"\x0fcollectInterval\x18\x06 \x01(\x03R\x0fcollectInterval\x12\"\n" +
	"\fcollectTimes\x18\a \x01(\x03R\fcollectTimes\"\xc4\x02\n" +
	"\x18CollectSwitchTrafficItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bisUplink\x18\x05 \x01(\bR\bisUplink\x12\x1e\n" +
	"\n" +
	"isDownlink\x18\x06 \x01(\bR\n" +
	"isDownlink\x12\"\n" +
	"\fisSpeedLimit\x18\a \x01(\bR\fisSpeedLimit\x12\"\n" +
	"\fpeakBusiness\x18\b \x01(\tR\fpeakBusiness\x12\x14\n" +
	"\x05alias\x18\t \x01(\tR\x05alias\x12.\n" +
	"\x05speed\x18\n" +
	" \x01(\v2\x13.vpn.IfTrafficSpeedH\x00R\x05speed\x88\x01\x01B\b\n" +
	"\x06_speed\"N\n" +
	"\x17CollectSwitchTrafficRes\x123\n" +
	"\x05Items\x18\x01 \x03(\v2\x1d.vpn.CollectSwitchTrafficItemR\x05Items\"~\n" +
	"\x0eIfTrafficSpeed\x12(\n" +
	"\x01t\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x01t\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12\x14\n" +
	"\x05inbps\x18\x03 \x01(\x01R\x05inbps\x12\x16\n" +
	"\x06outbps\x18\x04 \x01(\x01R\x06outbps\"}\n" +
	"\x13GetIfInLimitConfReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"privateKey\x18\x04 \x01(\tR\n" +
	"privateKey\"\x8d\x01\n" +
	"\x0fIfLimitConfItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x11qosInTemplateName\x18\x02 \x01(\tR\x11qosInTemplateName\x128\n" +
	"\rqosInTemplate\x18\x03 \x01(\v2\x12.vpn.QosInTemplateR\rqosInTemplate\"=\n" +
	"\rQosInTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aratebps\x18\x02 \x01(\x03R\aratebps\"A\n" +
	"\x13GetIfInLimitConfRes\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.vpn.IfLimitConfItemR\x05items\"\xac\x01\n" +
	"\n" +
	"IfLimitReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"privateKey\x18\x04 \x01(\tR\n" +
	"privateKey\x12\x1e\n" +
	"\n" +
	"limitValue\x18\x05 \x01(\x03R\n" +
	"limitValue\x12\x16\n" +
	"\x06ifName\x18\x06 \x01(\tR\x06ifName\"b\n" +
	"\n" +
	"IfLimitRes\x12\x1e\n" +
	"\n" +
	"consoleLog\x18\x01 \x01(\tR\n" +
	"consoleLog\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg\"\x8e\x01\n" +
	"\fIfUnlimitReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"privateKey\x18\x04 \x01(\tR\n" +
	"privateKey\x12\x16\n" +
	"\x06ifName\x18\x05 \x01(\tR\x06ifName\"d\n" +
	"\fIfUnlimitRes\x12\x1e\n" +
	"\n" +
	"consoleLog\x18\x01 \x01(\tR\n" +
	"consoleLog\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg\"\x8c\x01\n" +
	"\x10GetIfBaseInfoReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1c\n" +
	"\tcommunity\x18\x03 \x01(\tR\tcommunity\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x03R\x05retry\"\x80\x02\n" +
	"\x0eIfBaseInfoItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bisUplink\x18\x05 \x01(\bR\bisUplink\x12\x1e\n" +
	"\n" +
	"isDownlink\x18\x06 \x01(\bR\n" +
	"isDownlink\x12\"\n" +
	"\fisSpeedLimit\x18\a \x01(\bR\fisSpeedLimit\x12\"\n" +
	"\fpeakBusiness\x18\b \x01(\tR\fpeakBusiness\x12\x14\n" +
	"\x05alias\x18\t \x01(\tR\x05alias\"=\n" +
	"\x10GetIfBaseInfoRes\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.vpn.IfBaseInfoItemR\x05items\"\x92\x01\n" +
	"\x16GetIfTrafficCounterReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1c\n" +
	"\tcommunity\x18\x03 \x01(\tR\tcommunity\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x03R\x05retry\"\xc8\x01\n" +
	"\x14IfTrafficCounterItem\x122\n" +
	"\x06inTime\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06inTime\x124\n" +
	"\aoutTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aoutTime\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x03R\x05index\x12\x16\n" +
	"\x06inByte\x18\x04 \x01(\x04R\x06inByte\x12\x18\n" +
	"\aoutByte\x18\x05 \x01(\x04R\aoutByte\"I\n" +
	"\x16GetIfTrafficCounterRes\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.vpn.IfTrafficCounterItemR\x05items\"\xbb\x01\n" +
	"\x0fIfRangeLimitReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"privateKey\x18\x04 \x01(\tR\n" +
	"privateKey\x12\x1e\n" +
	"\n" +
	"limitValue\x18\x05 \x01(\x03R\n" +
	"limitValue\x12 \n" +
	"\vifNameRange\x18\x06 \x01(\tR\vifNameRange\"g\n" +
	"\x0fIfRangeLimitRes\x12\x1e\n" +
	"\n" +
	"consoleLog\x18\x01 \x01(\tR\n" +
	"consoleLog\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg\"\x9d\x01\n" +
	"\x11IfRangeUnlimitReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"privateKey\x18\x04 \x01(\tR\n" +
	"privateKey\x12 \n" +
	"\vifNameRange\x18\x05 \x01(\tR\vifNameRange\"i\n" +
	"\x11IfRangeUnlimitRes\x12\x1e\n" +
	"\n" +
	"consoleLog\x18\x01 \x01(\tR\n" +
	"consoleLog\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg2\x8f\x05\n" +
	"\n" +
	"VpnService\x12&\n" +
	"\x04Ping\x12\x10.common.EmptyReq\x1a\f.vpn.PingRes\x12O\n" +
	"\x13GetSwitchIfBusiness\x12\x1b.vpn.GetSwitchIfBusinessReq\x1a\x1b.vpn.GetSwitchIfBusinessRes\x12R\n" +
	"\x14CollectSwitchTraffic\x12\x1c.vpn.CollectSwitchTrafficReq\x1a\x1c.vpn.CollectSwitchTrafficRes\x12F\n" +
	"\x10GetIfInLimitConf\x12\x18.vpn.GetIfInLimitConfReq\x1a\x18.vpn.GetIfInLimitConfRes\x12+\n" +
	"\aIfLimit\x12\x0f.vpn.IfLimitReq\x1a\x0f.vpn.IfLimitRes\x121\n" +
	"\tIfUnlimit\x12\x11.vpn.IfUnlimitReq\x1a\x11.vpn.IfUnlimitRes\x12:\n" +
	"\fIfRangeLimit\x12\x14.vpn.IfRangeLimitReq\x1a\x14.vpn.IfRangeLimitRes\x12@\n" +
	"\x0eIfRangeUnlimit\x12\x16.vpn.IfRangeUnlimitReq\x1a\x16.vpn.IfRangeUnlimitRes\x12=\n" +
	"\rGetIfBaseInfo\x12\x15.vpn.GetIfBaseInfoReq\x1a\x15.vpn.GetIfBaseInfoRes\x12O\n" +
	"\x13GetIfTrafficCounter\x12\x1b.vpn.GetIfTrafficCounterReq\x1a\x1b.vpn.GetIfTrafficCounterResB\x1eZ\x1cbiz-auto-api/pkg/grpc/pb/vpnb\x06proto3"

var (
	file_internal_apps_vpn_proto_vpn_proto_rawDescOnce sync.Once
	file_internal_apps_vpn_proto_vpn_proto_rawDescData []byte
)

func file_internal_apps_vpn_proto_vpn_proto_rawDescGZIP() []byte {
	file_internal_apps_vpn_proto_vpn_proto_rawDescOnce.Do(func() {
		file_internal_apps_vpn_proto_vpn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_apps_vpn_proto_vpn_proto_rawDesc), len(file_internal_apps_vpn_proto_vpn_proto_rawDesc)))
	})
	return file_internal_apps_vpn_proto_vpn_proto_rawDescData
}

var file_internal_apps_vpn_proto_vpn_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_internal_apps_vpn_proto_vpn_proto_goTypes = []any{
	(*PingRes)(nil),                  // 0: vpn.PingRes
	(*GetSwitchIfBusinessReq)(nil),   // 1: vpn.GetSwitchIfBusinessReq
	(*GetSwitchIfBusinessRes)(nil),   // 2: vpn.GetSwitchIfBusinessRes
	(*CollectSwitchTrafficReq)(nil),  // 3: vpn.CollectSwitchTrafficReq
	(*CollectSwitchTrafficItem)(nil), // 4: vpn.CollectSwitchTrafficItem
	(*CollectSwitchTrafficRes)(nil),  // 5: vpn.CollectSwitchTrafficRes
	(*IfTrafficSpeed)(nil),           // 6: vpn.IfTrafficSpeed
	(*GetIfInLimitConfReq)(nil),      // 7: vpn.GetIfInLimitConfReq
	(*IfLimitConfItem)(nil),          // 8: vpn.IfLimitConfItem
	(*QosInTemplate)(nil),            // 9: vpn.QosInTemplate
	(*GetIfInLimitConfRes)(nil),      // 10: vpn.GetIfInLimitConfRes
	(*IfLimitReq)(nil),               // 11: vpn.IfLimitReq
	(*IfLimitRes)(nil),               // 12: vpn.IfLimitRes
	(*IfUnlimitReq)(nil),             // 13: vpn.IfUnlimitReq
	(*IfUnlimitRes)(nil),             // 14: vpn.IfUnlimitRes
	(*GetIfBaseInfoReq)(nil),         // 15: vpn.GetIfBaseInfoReq
	(*IfBaseInfoItem)(nil),           // 16: vpn.IfBaseInfoItem
	(*GetIfBaseInfoRes)(nil),         // 17: vpn.GetIfBaseInfoRes
	(*GetIfTrafficCounterReq)(nil),   // 18: vpn.GetIfTrafficCounterReq
	(*IfTrafficCounterItem)(nil),     // 19: vpn.IfTrafficCounterItem
	(*GetIfTrafficCounterRes)(nil),   // 20: vpn.GetIfTrafficCounterRes
	(*IfRangeLimitReq)(nil),          // 21: vpn.IfRangeLimitReq
	(*IfRangeLimitRes)(nil),          // 22: vpn.IfRangeLimitRes
	(*IfRangeUnlimitReq)(nil),        // 23: vpn.IfRangeUnlimitReq
	(*IfRangeUnlimitRes)(nil),        // 24: vpn.IfRangeUnlimitRes
	(*timestamppb.Timestamp)(nil),    // 25: google.protobuf.Timestamp
	(*common.EmptyReq)(nil),          // 26: common.EmptyReq
}
var file_internal_apps_vpn_proto_vpn_proto_depIdxs = []int32{
	6,  // 0: vpn.CollectSwitchTrafficItem.speed:type_name -> vpn.IfTrafficSpeed
	4,  // 1: vpn.CollectSwitchTrafficRes.Items:type_name -> vpn.CollectSwitchTrafficItem
	25, // 2: vpn.IfTrafficSpeed.t:type_name -> google.protobuf.Timestamp
	9,  // 3: vpn.IfLimitConfItem.qosInTemplate:type_name -> vpn.QosInTemplate
	8,  // 4: vpn.GetIfInLimitConfRes.items:type_name -> vpn.IfLimitConfItem
	16, // 5: vpn.GetIfBaseInfoRes.items:type_name -> vpn.IfBaseInfoItem
	25, // 6: vpn.IfTrafficCounterItem.inTime:type_name -> google.protobuf.Timestamp
	25, // 7: vpn.IfTrafficCounterItem.outTime:type_name -> google.protobuf.Timestamp
	19, // 8: vpn.GetIfTrafficCounterRes.items:type_name -> vpn.IfTrafficCounterItem
	26, // 9: vpn.VpnService.Ping:input_type -> common.EmptyReq
	1,  // 10: vpn.VpnService.GetSwitchIfBusiness:input_type -> vpn.GetSwitchIfBusinessReq
	3,  // 11: vpn.VpnService.CollectSwitchTraffic:input_type -> vpn.CollectSwitchTrafficReq
	7,  // 12: vpn.VpnService.GetIfInLimitConf:input_type -> vpn.GetIfInLimitConfReq
	11, // 13: vpn.VpnService.IfLimit:input_type -> vpn.IfLimitReq
	13, // 14: vpn.VpnService.IfUnlimit:input_type -> vpn.IfUnlimitReq
	21, // 15: vpn.VpnService.IfRangeLimit:input_type -> vpn.IfRangeLimitReq
	23, // 16: vpn.VpnService.IfRangeUnlimit:input_type -> vpn.IfRangeUnlimitReq
	15, // 17: vpn.VpnService.GetIfBaseInfo:input_type -> vpn.GetIfBaseInfoReq
	18, // 18: vpn.VpnService.GetIfTrafficCounter:input_type -> vpn.GetIfTrafficCounterReq
	0,  // 19: vpn.VpnService.Ping:output_type -> vpn.PingRes
	2,  // 20: vpn.VpnService.GetSwitchIfBusiness:output_type -> vpn.GetSwitchIfBusinessRes
	5,  // 21: vpn.VpnService.CollectSwitchTraffic:output_type -> vpn.CollectSwitchTrafficRes
	10, // 22: vpn.VpnService.GetIfInLimitConf:output_type -> vpn.GetIfInLimitConfRes
	12, // 23: vpn.VpnService.IfLimit:output_type -> vpn.IfLimitRes
	14, // 24: vpn.VpnService.IfUnlimit:output_type -> vpn.IfUnlimitRes
	22, // 25: vpn.VpnService.IfRangeLimit:output_type -> vpn.IfRangeLimitRes
	24, // 26: vpn.VpnService.IfRangeUnlimit:output_type -> vpn.IfRangeUnlimitRes
	17, // 27: vpn.VpnService.GetIfBaseInfo:output_type -> vpn.GetIfBaseInfoRes
	20, // 28: vpn.VpnService.GetIfTrafficCounter:output_type -> vpn.GetIfTrafficCounterRes
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_apps_vpn_proto_vpn_proto_init() }
func file_internal_apps_vpn_proto_vpn_proto_init() {
	if File_internal_apps_vpn_proto_vpn_proto != nil {
		return
	}
	file_internal_apps_vpn_proto_vpn_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_apps_vpn_proto_vpn_proto_rawDesc), len(file_internal_apps_vpn_proto_vpn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_apps_vpn_proto_vpn_proto_goTypes,
		DependencyIndexes: file_internal_apps_vpn_proto_vpn_proto_depIdxs,
		MessageInfos:      file_internal_apps_vpn_proto_vpn_proto_msgTypes,
	}.Build()
	File_internal_apps_vpn_proto_vpn_proto = out.File
	file_internal_apps_vpn_proto_vpn_proto_goTypes = nil
	file_internal_apps_vpn_proto_vpn_proto_depIdxs = nil
}
