// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: internal/apps/vpn/proto/vpn.proto

package vpn

import (
	common "biz-auto-api/pkg/grpc/pb/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VpnService_Ping_FullMethodName                 = "/vpn.VpnService/Ping"
	VpnService_GetSwitchIfBusiness_FullMethodName  = "/vpn.VpnService/GetSwitchIfBusiness"
	VpnService_CollectSwitchTraffic_FullMethodName = "/vpn.VpnService/CollectSwitchTraffic"
	VpnService_GetIfInLimitConf_FullMethodName     = "/vpn.VpnService/GetIfInLimitConf"
	VpnService_IfLimit_FullMethodName              = "/vpn.VpnService/IfLimit"
	VpnService_IfUnlimit_FullMethodName            = "/vpn.VpnService/IfUnlimit"
	VpnService_IfRangeLimit_FullMethodName         = "/vpn.VpnService/IfRangeLimit"
	VpnService_IfRangeUnlimit_FullMethodName       = "/vpn.VpnService/IfRangeUnlimit"
	VpnService_GetIfBaseInfo_FullMethodName        = "/vpn.VpnService/GetIfBaseInfo"
	VpnService_GetIfTrafficCounter_FullMethodName  = "/vpn.VpnService/GetIfTrafficCounter"
)

// VpnServiceClient is the client API for VpnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnServiceClient interface {
	Ping(ctx context.Context, in *common.EmptyReq, opts ...grpc.CallOption) (*PingRes, error)
	GetSwitchIfBusiness(ctx context.Context, in *GetSwitchIfBusinessReq, opts ...grpc.CallOption) (*GetSwitchIfBusinessRes, error)
	CollectSwitchTraffic(ctx context.Context, in *CollectSwitchTrafficReq, opts ...grpc.CallOption) (*CollectSwitchTrafficRes, error)
	GetIfInLimitConf(ctx context.Context, in *GetIfInLimitConfReq, opts ...grpc.CallOption) (*GetIfInLimitConfRes, error)
	IfLimit(ctx context.Context, in *IfLimitReq, opts ...grpc.CallOption) (*IfLimitRes, error)
	IfUnlimit(ctx context.Context, in *IfUnlimitReq, opts ...grpc.CallOption) (*IfUnlimitRes, error)
	IfRangeLimit(ctx context.Context, in *IfRangeLimitReq, opts ...grpc.CallOption) (*IfRangeLimitRes, error)
	IfRangeUnlimit(ctx context.Context, in *IfRangeUnlimitReq, opts ...grpc.CallOption) (*IfRangeUnlimitRes, error)
	GetIfBaseInfo(ctx context.Context, in *GetIfBaseInfoReq, opts ...grpc.CallOption) (*GetIfBaseInfoRes, error)
	GetIfTrafficCounter(ctx context.Context, in *GetIfTrafficCounterReq, opts ...grpc.CallOption) (*GetIfTrafficCounterRes, error)
}

type vpnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnServiceClient(cc grpc.ClientConnInterface) VpnServiceClient {
	return &vpnServiceClient{cc}
}

func (c *vpnServiceClient) Ping(ctx context.Context, in *common.EmptyReq, opts ...grpc.CallOption) (*PingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingRes)
	err := c.cc.Invoke(ctx, VpnService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) GetSwitchIfBusiness(ctx context.Context, in *GetSwitchIfBusinessReq, opts ...grpc.CallOption) (*GetSwitchIfBusinessRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwitchIfBusinessRes)
	err := c.cc.Invoke(ctx, VpnService_GetSwitchIfBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) CollectSwitchTraffic(ctx context.Context, in *CollectSwitchTrafficReq, opts ...grpc.CallOption) (*CollectSwitchTrafficRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectSwitchTrafficRes)
	err := c.cc.Invoke(ctx, VpnService_CollectSwitchTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) GetIfInLimitConf(ctx context.Context, in *GetIfInLimitConfReq, opts ...grpc.CallOption) (*GetIfInLimitConfRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIfInLimitConfRes)
	err := c.cc.Invoke(ctx, VpnService_GetIfInLimitConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) IfLimit(ctx context.Context, in *IfLimitReq, opts ...grpc.CallOption) (*IfLimitRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IfLimitRes)
	err := c.cc.Invoke(ctx, VpnService_IfLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) IfUnlimit(ctx context.Context, in *IfUnlimitReq, opts ...grpc.CallOption) (*IfUnlimitRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IfUnlimitRes)
	err := c.cc.Invoke(ctx, VpnService_IfUnlimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) IfRangeLimit(ctx context.Context, in *IfRangeLimitReq, opts ...grpc.CallOption) (*IfRangeLimitRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IfRangeLimitRes)
	err := c.cc.Invoke(ctx, VpnService_IfRangeLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) IfRangeUnlimit(ctx context.Context, in *IfRangeUnlimitReq, opts ...grpc.CallOption) (*IfRangeUnlimitRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IfRangeUnlimitRes)
	err := c.cc.Invoke(ctx, VpnService_IfRangeUnlimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) GetIfBaseInfo(ctx context.Context, in *GetIfBaseInfoReq, opts ...grpc.CallOption) (*GetIfBaseInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIfBaseInfoRes)
	err := c.cc.Invoke(ctx, VpnService_GetIfBaseInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnServiceClient) GetIfTrafficCounter(ctx context.Context, in *GetIfTrafficCounterReq, opts ...grpc.CallOption) (*GetIfTrafficCounterRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIfTrafficCounterRes)
	err := c.cc.Invoke(ctx, VpnService_GetIfTrafficCounter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnServiceServer is the server API for VpnService service.
// All implementations must embed UnimplementedVpnServiceServer
// for forward compatibility.
type VpnServiceServer interface {
	Ping(context.Context, *common.EmptyReq) (*PingRes, error)
	GetSwitchIfBusiness(context.Context, *GetSwitchIfBusinessReq) (*GetSwitchIfBusinessRes, error)
	CollectSwitchTraffic(context.Context, *CollectSwitchTrafficReq) (*CollectSwitchTrafficRes, error)
	GetIfInLimitConf(context.Context, *GetIfInLimitConfReq) (*GetIfInLimitConfRes, error)
	IfLimit(context.Context, *IfLimitReq) (*IfLimitRes, error)
	IfUnlimit(context.Context, *IfUnlimitReq) (*IfUnlimitRes, error)
	IfRangeLimit(context.Context, *IfRangeLimitReq) (*IfRangeLimitRes, error)
	IfRangeUnlimit(context.Context, *IfRangeUnlimitReq) (*IfRangeUnlimitRes, error)
	GetIfBaseInfo(context.Context, *GetIfBaseInfoReq) (*GetIfBaseInfoRes, error)
	GetIfTrafficCounter(context.Context, *GetIfTrafficCounterReq) (*GetIfTrafficCounterRes, error)
	mustEmbedUnimplementedVpnServiceServer()
}

// UnimplementedVpnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnServiceServer struct{}

func (UnimplementedVpnServiceServer) Ping(context.Context, *common.EmptyReq) (*PingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedVpnServiceServer) GetSwitchIfBusiness(context.Context, *GetSwitchIfBusinessReq) (*GetSwitchIfBusinessRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSwitchIfBusiness not implemented")
}
func (UnimplementedVpnServiceServer) CollectSwitchTraffic(context.Context, *CollectSwitchTrafficReq) (*CollectSwitchTrafficRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectSwitchTraffic not implemented")
}
func (UnimplementedVpnServiceServer) GetIfInLimitConf(context.Context, *GetIfInLimitConfReq) (*GetIfInLimitConfRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIfInLimitConf not implemented")
}
func (UnimplementedVpnServiceServer) IfLimit(context.Context, *IfLimitReq) (*IfLimitRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IfLimit not implemented")
}
func (UnimplementedVpnServiceServer) IfUnlimit(context.Context, *IfUnlimitReq) (*IfUnlimitRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IfUnlimit not implemented")
}
func (UnimplementedVpnServiceServer) IfRangeLimit(context.Context, *IfRangeLimitReq) (*IfRangeLimitRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IfRangeLimit not implemented")
}
func (UnimplementedVpnServiceServer) IfRangeUnlimit(context.Context, *IfRangeUnlimitReq) (*IfRangeUnlimitRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IfRangeUnlimit not implemented")
}
func (UnimplementedVpnServiceServer) GetIfBaseInfo(context.Context, *GetIfBaseInfoReq) (*GetIfBaseInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIfBaseInfo not implemented")
}
func (UnimplementedVpnServiceServer) GetIfTrafficCounter(context.Context, *GetIfTrafficCounterReq) (*GetIfTrafficCounterRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIfTrafficCounter not implemented")
}
func (UnimplementedVpnServiceServer) mustEmbedUnimplementedVpnServiceServer() {}
func (UnimplementedVpnServiceServer) testEmbeddedByValue()                    {}

// UnsafeVpnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnServiceServer will
// result in compilation errors.
type UnsafeVpnServiceServer interface {
	mustEmbedUnimplementedVpnServiceServer()
}

func RegisterVpnServiceServer(s grpc.ServiceRegistrar, srv VpnServiceServer) {
	// If the following call pancis, it indicates UnimplementedVpnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VpnService_ServiceDesc, srv)
}

func _VpnService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).Ping(ctx, req.(*common.EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_GetSwitchIfBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwitchIfBusinessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).GetSwitchIfBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_GetSwitchIfBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).GetSwitchIfBusiness(ctx, req.(*GetSwitchIfBusinessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_CollectSwitchTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectSwitchTrafficReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).CollectSwitchTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_CollectSwitchTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).CollectSwitchTraffic(ctx, req.(*CollectSwitchTrafficReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_GetIfInLimitConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIfInLimitConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).GetIfInLimitConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_GetIfInLimitConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).GetIfInLimitConf(ctx, req.(*GetIfInLimitConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_IfLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IfLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).IfLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_IfLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).IfLimit(ctx, req.(*IfLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_IfUnlimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IfUnlimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).IfUnlimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_IfUnlimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).IfUnlimit(ctx, req.(*IfUnlimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_IfRangeLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IfRangeLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).IfRangeLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_IfRangeLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).IfRangeLimit(ctx, req.(*IfRangeLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_IfRangeUnlimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IfRangeUnlimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).IfRangeUnlimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_IfRangeUnlimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).IfRangeUnlimit(ctx, req.(*IfRangeUnlimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_GetIfBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIfBaseInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).GetIfBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_GetIfBaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).GetIfBaseInfo(ctx, req.(*GetIfBaseInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnService_GetIfTrafficCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIfTrafficCounterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServiceServer).GetIfTrafficCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnService_GetIfTrafficCounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServiceServer).GetIfTrafficCounter(ctx, req.(*GetIfTrafficCounterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VpnService_ServiceDesc is the grpc.ServiceDesc for VpnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VpnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vpn.VpnService",
	HandlerType: (*VpnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _VpnService_Ping_Handler,
		},
		{
			MethodName: "GetSwitchIfBusiness",
			Handler:    _VpnService_GetSwitchIfBusiness_Handler,
		},
		{
			MethodName: "CollectSwitchTraffic",
			Handler:    _VpnService_CollectSwitchTraffic_Handler,
		},
		{
			MethodName: "GetIfInLimitConf",
			Handler:    _VpnService_GetIfInLimitConf_Handler,
		},
		{
			MethodName: "IfLimit",
			Handler:    _VpnService_IfLimit_Handler,
		},
		{
			MethodName: "IfUnlimit",
			Handler:    _VpnService_IfUnlimit_Handler,
		},
		{
			MethodName: "IfRangeLimit",
			Handler:    _VpnService_IfRangeLimit_Handler,
		},
		{
			MethodName: "IfRangeUnlimit",
			Handler:    _VpnService_IfRangeUnlimit_Handler,
		},
		{
			MethodName: "GetIfBaseInfo",
			Handler:    _VpnService_GetIfBaseInfo_Handler,
		},
		{
			MethodName: "GetIfTrafficCounter",
			Handler:    _VpnService_GetIfTrafficCounter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/apps/vpn/proto/vpn.proto",
}
