export const testData = [
  {
    id: 1,
    parentId: 0,
    name: '公共操作',
    businessId: 10,
    type: 'group',
    description: null,
    scriptName: null,
    scriptPath: null,
    timeout: 300,
    maxHosts: 0,
    sort: 0,
    status: 1,
    isRoot: true,
    createBy: 0,
    createdAt: '2025-11-18T10:07:02+08:00',
    updatedAt: '0001-01-01T00:00:00Z',
    children: [
      {
        id: 14,
        parentId: 1,
        name: 'Z测试',
        businessId: 10,
        type: 'function',
        description: '',
        scriptName: 'version.sh',
        scriptPath: '/etc/zabbix/scripts/general/agent/',
        timeout: 1,
        maxHosts: 1,
        sort: 0,
        status: 1,
        isRoot: false,
        createBy: 441,
        createdAt: '2025-11-18T15:46:49+08:00',
        updatedAt: '2025-11-20T13:53:01+08:00',
        params: [
          {
            name: '配置类型',
            default: '',
            required: true,
            options: [
              {
                label: 'SSH文件配置',
                value: '--path /root/.ssh/authorized_keys',
                params: ['操作类型'],
              },
              {
                label: 'Frpc文件配置',
                value: '--path /etc/frpc/frpc.ini',
                params: ['操作类型'],
              },
              {
                label: '其他配置文件',
                value: '--path',
                params: ['其他配置文件路径', '操作类型'],
              },
            ],
            type: 'select',
          },
          {
            name: '其他配置文件路径',
            default: '',
            required: false,
            type: 'input',
          },
          {
            name: '操作类型',
            default: '',
            required: true,
            options: [
              {
                label: '新增',
                value: 'add',
                params: ['空跑', '新增内容'],
              },
              {
                label: '删除',
                value: 'delete --match',
                params: ['空跑', '删除内容'],
              },
              {
                label: '修改',
                value: 'modify --match',
                params: ['空跑', '修改前内容', '修改后内容'],
              },
              {
                label: '查询',
                value: 'query',
              },
            ],
            type: 'select',
          },
          {
            name: '新增内容',
            default: '',
            required: false,
            type: 'input',
            help: '需要新增的配置内容',
          },
          {
            name: '删除内容',
            default: '',
            required: false,
            type: 'input',
            help: '删除匹配到的所有内容,请务必保证匹配是唯一',
          },
          {
            name: '修改前内容',
            default: '',
            required: false,
            type: 'input',
            help: '修改前内容,保证匹配唯一',
          },
          {
            name: '修改后内容',
            default: '',
            required: false,
            type: 'input',
            help: '修改后内容',
          },
          {
            name: '查看指定内容',
            default: '',
            required: false,
            type: 'input',
          },
          {
            name: '空跑',
            default: '',
            required: false,
            options: [
              {
                label: '是',
                value: '--dry-run',
              },
              {
                label: '否',
                value: '',
              },
            ],
            type: 'select',
          },
        ],
      },
    ],
  },
];
