// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/apps/auth/proto/auth.proto

package auth

import (
	common "biz-auto-api/pkg/grpc/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRes) Reset() {
	*x = PingRes{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRes) ProtoMessage() {}

func (x *PingRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRes.ProtoReflect.Descriptor instead.
func (*PingRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *PingRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CheckPermissionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required,gt=0"
	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty" validate:"required,gt=0"`
	// @gotags: validate:"required"
	ResType string `protobuf:"bytes,2,opt,name=resType,proto3" json:"resType,omitempty" validate:"required"`
	// @gotags: validate:"required"
	ResID string `protobuf:"bytes,3,opt,name=resID,proto3" json:"resID,omitempty" validate:"required"`
	// @gotags: validate:"required"
	Action        string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionReq) Reset() {
	*x = CheckPermissionReq{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionReq) ProtoMessage() {}

func (x *CheckPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionReq.ProtoReflect.Descriptor instead.
func (*CheckPermissionReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPermissionReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CheckPermissionReq) GetResType() string {
	if x != nil {
		return x.ResType
	}
	return ""
}

func (x *CheckPermissionReq) GetResID() string {
	if x != nil {
		return x.ResID
	}
	return ""
}

func (x *CheckPermissionReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CheckPermissionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRes) Reset() {
	*x = CheckPermissionRes{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRes) ProtoMessage() {}

func (x *CheckPermissionRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRes.ProtoReflect.Descriptor instead.
func (*CheckPermissionRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CheckPermissionRes) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type GetUserAuthorizedResIdsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required,gt=0"
	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty" validate:"required,gt=0"`
	// @gotags: validate:"required"
	ResType string `protobuf:"bytes,2,opt,name=resType,proto3" json:"resType,omitempty" validate:"required"`
	// @gotags: validate:"required"
	Action        string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthorizedResIdsReq) Reset() {
	*x = GetUserAuthorizedResIdsReq{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorizedResIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorizedResIdsReq) ProtoMessage() {}

func (x *GetUserAuthorizedResIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorizedResIdsReq.ProtoReflect.Descriptor instead.
func (*GetUserAuthorizedResIdsReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserAuthorizedResIdsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetUserAuthorizedResIdsReq) GetResType() string {
	if x != nil {
		return x.ResType
	}
	return ""
}

func (x *GetUserAuthorizedResIdsReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type GetUserAuthorizedResIdsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResIds        []int64                `protobuf:"varint,1,rep,packed,name=resIds,proto3" json:"resIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthorizedResIdsRes) Reset() {
	*x = GetUserAuthorizedResIdsRes{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorizedResIdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorizedResIdsRes) ProtoMessage() {}

func (x *GetUserAuthorizedResIdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorizedResIdsRes.ProtoReflect.Descriptor instead.
func (*GetUserAuthorizedResIdsRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserAuthorizedResIdsRes) GetResIds() []int64 {
	if x != nil {
		return x.ResIds
	}
	return nil
}

type GetUserAuthorizedResFieldsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required,gt=0"
	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty" validate:"required,gt=0"`
	// @gotags: validate:"required"
	ResType string `protobuf:"bytes,2,opt,name=resType,proto3" json:"resType,omitempty" validate:"required"`
	// @gotags: validate:"required"
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty" validate:"required"`
	// @gotags: validate:"required"
	FieldName     string `protobuf:"bytes,4,opt,name=fieldName,proto3" json:"fieldName,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthorizedResFieldsReq) Reset() {
	*x = GetUserAuthorizedResFieldsReq{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorizedResFieldsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorizedResFieldsReq) ProtoMessage() {}

func (x *GetUserAuthorizedResFieldsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorizedResFieldsReq.ProtoReflect.Descriptor instead.
func (*GetUserAuthorizedResFieldsReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserAuthorizedResFieldsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetUserAuthorizedResFieldsReq) GetResType() string {
	if x != nil {
		return x.ResType
	}
	return ""
}

func (x *GetUserAuthorizedResFieldsReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GetUserAuthorizedResFieldsReq) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type GetUserAuthorizedResFieldsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldValues   []string               `protobuf:"bytes,1,rep,name=fieldValues,proto3" json:"fieldValues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthorizedResFieldsRes) Reset() {
	*x = GetUserAuthorizedResFieldsRes{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorizedResFieldsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorizedResFieldsRes) ProtoMessage() {}

func (x *GetUserAuthorizedResFieldsRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorizedResFieldsRes.ProtoReflect.Descriptor instead.
func (*GetUserAuthorizedResFieldsRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserAuthorizedResFieldsRes) GetFieldValues() []string {
	if x != nil {
		return x.FieldValues
	}
	return nil
}

type GetUserAuthorizedResIdsSQLReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required,gt=0"
	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty" validate:"required,gt=0"`
	// @gotags: validate:"required"
	ResType string `protobuf:"bytes,2,opt,name=resType,proto3" json:"resType,omitempty" validate:"required"`
	// @gotags: validate:"required"
	Action        string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthorizedResIdsSQLReq) Reset() {
	*x = GetUserAuthorizedResIdsSQLReq{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorizedResIdsSQLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorizedResIdsSQLReq) ProtoMessage() {}

func (x *GetUserAuthorizedResIdsSQLReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorizedResIdsSQLReq.ProtoReflect.Descriptor instead.
func (*GetUserAuthorizedResIdsSQLReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserAuthorizedResIdsSQLReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetUserAuthorizedResIdsSQLReq) GetResType() string {
	if x != nil {
		return x.ResType
	}
	return ""
}

func (x *GetUserAuthorizedResIdsSQLReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type GetUserAuthorizedResIdsSQLRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthorizedResIdsSQLRes) Reset() {
	*x = GetUserAuthorizedResIdsSQLRes{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorizedResIdsSQLRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorizedResIdsSQLRes) ProtoMessage() {}

func (x *GetUserAuthorizedResIdsSQLRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorizedResIdsSQLRes.ProtoReflect.Descriptor instead.
func (*GetUserAuthorizedResIdsSQLRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserAuthorizedResIdsSQLRes) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type GetUserAuthorizedResFieldsSQLReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: validate:"required,gt=0"
	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty" validate:"required,gt=0"`
	// @gotags: validate:"required"
	ResType string `protobuf:"bytes,2,opt,name=resType,proto3" json:"resType,omitempty" validate:"required"`
	// @gotags: validate:"required"
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty" validate:"required"`
	// @gotags: validate:"required"
	FieldName     string `protobuf:"bytes,4,opt,name=fieldName,proto3" json:"fieldName,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthorizedResFieldsSQLReq) Reset() {
	*x = GetUserAuthorizedResFieldsSQLReq{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorizedResFieldsSQLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorizedResFieldsSQLReq) ProtoMessage() {}

func (x *GetUserAuthorizedResFieldsSQLReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorizedResFieldsSQLReq.ProtoReflect.Descriptor instead.
func (*GetUserAuthorizedResFieldsSQLReq) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserAuthorizedResFieldsSQLReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetUserAuthorizedResFieldsSQLReq) GetResType() string {
	if x != nil {
		return x.ResType
	}
	return ""
}

func (x *GetUserAuthorizedResFieldsSQLReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GetUserAuthorizedResFieldsSQLReq) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type GetUserAuthorizedResFieldsSQLRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthorizedResFieldsSQLRes) Reset() {
	*x = GetUserAuthorizedResFieldsSQLRes{}
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorizedResFieldsSQLRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorizedResFieldsSQLRes) ProtoMessage() {}

func (x *GetUserAuthorizedResFieldsSQLRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apps_auth_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorizedResFieldsSQLRes.ProtoReflect.Descriptor instead.
func (*GetUserAuthorizedResFieldsSQLRes) Descriptor() ([]byte, []int) {
	return file_internal_apps_auth_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserAuthorizedResFieldsSQLRes) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

var File_internal_apps_auth_proto_auth_proto protoreflect.FileDescriptor

const file_internal_apps_auth_proto_auth_proto_rawDesc = "" +
	"\n" +
	"#internal/apps/auth/proto/auth.proto\x12\x04auth\x1a\x1bpkg/grpc/proto/common.proto\"\x1b\n" +
	"\aPingRes\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"t\n" +
	"\x12CheckPermissionReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x18\n" +
	"\aresType\x18\x02 \x01(\tR\aresType\x12\x14\n" +
	"\x05resID\x18\x03 \x01(\tR\x05resID\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\".\n" +
	"\x12CheckPermissionRes\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"f\n" +
	"\x1aGetUserAuthorizedResIdsReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x18\n" +
	"\aresType\x18\x02 \x01(\tR\aresType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"4\n" +
	"\x1aGetUserAuthorizedResIdsRes\x12\x16\n" +
	"\x06resIds\x18\x01 \x03(\x03R\x06resIds\"\x87\x01\n" +
	"\x1dGetUserAuthorizedResFieldsReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x18\n" +
	"\aresType\x18\x02 \x01(\tR\aresType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1c\n" +
	"\tfieldName\x18\x04 \x01(\tR\tfieldName\"A\n" +
	"\x1dGetUserAuthorizedResFieldsRes\x12 \n" +
	"\vfieldValues\x18\x01 \x03(\tR\vfieldValues\"i\n" +
	"\x1dGetUserAuthorizedResIdsSQLReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x18\n" +
	"\aresType\x18\x02 \x01(\tR\aresType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"1\n" +
	"\x1dGetUserAuthorizedResIdsSQLRes\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"\x8a\x01\n" +
	" GetUserAuthorizedResFieldsSQLReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x18\n" +
	"\aresType\x18\x02 \x01(\tR\aresType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1c\n" +
	"\tfieldName\x18\x04 \x01(\tR\tfieldName\"4\n" +
	" GetUserAuthorizedResFieldsSQLRes\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql2\x9d\x04\n" +
	"\vAuthService\x12'\n" +
	"\x04Ping\x12\x10.common.EmptyReq\x1a\r.auth.PingRes\x12E\n" +
	"\x0fCheckPermission\x12\x18.auth.CheckPermissionReq\x1a\x18.auth.CheckPermissionRes\x12]\n" +
	"\x17GetUserAuthorizedResIds\x12 .auth.GetUserAuthorizedResIdsReq\x1a .auth.GetUserAuthorizedResIdsRes\x12f\n" +
	"\x1aGetUserAuthorizedResFields\x12#.auth.GetUserAuthorizedResFieldsReq\x1a#.auth.GetUserAuthorizedResFieldsRes\x12f\n" +
	"\x1aGetUserAuthorizedResIdsSQL\x12#.auth.GetUserAuthorizedResIdsSQLReq\x1a#.auth.GetUserAuthorizedResIdsSQLRes\x12o\n" +
	"\x1dGetUserAuthorizedResFieldsSQL\x12&.auth.GetUserAuthorizedResFieldsSQLReq\x1a&.auth.GetUserAuthorizedResFieldsSQLResB\x1fZ\x1dbiz-auto-api/pkg/grpc/pb/authb\x06proto3"

var (
	file_internal_apps_auth_proto_auth_proto_rawDescOnce sync.Once
	file_internal_apps_auth_proto_auth_proto_rawDescData []byte
)

func file_internal_apps_auth_proto_auth_proto_rawDescGZIP() []byte {
	file_internal_apps_auth_proto_auth_proto_rawDescOnce.Do(func() {
		file_internal_apps_auth_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_apps_auth_proto_auth_proto_rawDesc), len(file_internal_apps_auth_proto_auth_proto_rawDesc)))
	})
	return file_internal_apps_auth_proto_auth_proto_rawDescData
}

var file_internal_apps_auth_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_apps_auth_proto_auth_proto_goTypes = []any{
	(*PingRes)(nil),                          // 0: auth.PingRes
	(*CheckPermissionReq)(nil),               // 1: auth.CheckPermissionReq
	(*CheckPermissionRes)(nil),               // 2: auth.CheckPermissionRes
	(*GetUserAuthorizedResIdsReq)(nil),       // 3: auth.GetUserAuthorizedResIdsReq
	(*GetUserAuthorizedResIdsRes)(nil),       // 4: auth.GetUserAuthorizedResIdsRes
	(*GetUserAuthorizedResFieldsReq)(nil),    // 5: auth.GetUserAuthorizedResFieldsReq
	(*GetUserAuthorizedResFieldsRes)(nil),    // 6: auth.GetUserAuthorizedResFieldsRes
	(*GetUserAuthorizedResIdsSQLReq)(nil),    // 7: auth.GetUserAuthorizedResIdsSQLReq
	(*GetUserAuthorizedResIdsSQLRes)(nil),    // 8: auth.GetUserAuthorizedResIdsSQLRes
	(*GetUserAuthorizedResFieldsSQLReq)(nil), // 9: auth.GetUserAuthorizedResFieldsSQLReq
	(*GetUserAuthorizedResFieldsSQLRes)(nil), // 10: auth.GetUserAuthorizedResFieldsSQLRes
	(*common.EmptyReq)(nil),                  // 11: common.EmptyReq
}
var file_internal_apps_auth_proto_auth_proto_depIdxs = []int32{
	11, // 0: auth.AuthService.Ping:input_type -> common.EmptyReq
	1,  // 1: auth.AuthService.CheckPermission:input_type -> auth.CheckPermissionReq
	3,  // 2: auth.AuthService.GetUserAuthorizedResIds:input_type -> auth.GetUserAuthorizedResIdsReq
	5,  // 3: auth.AuthService.GetUserAuthorizedResFields:input_type -> auth.GetUserAuthorizedResFieldsReq
	7,  // 4: auth.AuthService.GetUserAuthorizedResIdsSQL:input_type -> auth.GetUserAuthorizedResIdsSQLReq
	9,  // 5: auth.AuthService.GetUserAuthorizedResFieldsSQL:input_type -> auth.GetUserAuthorizedResFieldsSQLReq
	0,  // 6: auth.AuthService.Ping:output_type -> auth.PingRes
	2,  // 7: auth.AuthService.CheckPermission:output_type -> auth.CheckPermissionRes
	4,  // 8: auth.AuthService.GetUserAuthorizedResIds:output_type -> auth.GetUserAuthorizedResIdsRes
	6,  // 9: auth.AuthService.GetUserAuthorizedResFields:output_type -> auth.GetUserAuthorizedResFieldsRes
	8,  // 10: auth.AuthService.GetUserAuthorizedResIdsSQL:output_type -> auth.GetUserAuthorizedResIdsSQLRes
	10, // 11: auth.AuthService.GetUserAuthorizedResFieldsSQL:output_type -> auth.GetUserAuthorizedResFieldsSQLRes
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_apps_auth_proto_auth_proto_init() }
func file_internal_apps_auth_proto_auth_proto_init() {
	if File_internal_apps_auth_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_apps_auth_proto_auth_proto_rawDesc), len(file_internal_apps_auth_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_apps_auth_proto_auth_proto_goTypes,
		DependencyIndexes: file_internal_apps_auth_proto_auth_proto_depIdxs,
		MessageInfos:      file_internal_apps_auth_proto_auth_proto_msgTypes,
	}.Build()
	File_internal_apps_auth_proto_auth_proto = out.File
	file_internal_apps_auth_proto_auth_proto_goTypes = nil
	file_internal_apps_auth_proto_auth_proto_depIdxs = nil
}
