// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: internal/apps/auth/proto/auth.proto

package auth

import (
	common "biz-auto-api/pkg/grpc/pb/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Ping_FullMethodName                          = "/auth.AuthService/Ping"
	AuthService_CheckPermission_FullMethodName               = "/auth.AuthService/CheckPermission"
	AuthService_GetUserAuthorizedResIds_FullMethodName       = "/auth.AuthService/GetUserAuthorizedResIds"
	AuthService_GetUserAuthorizedResFields_FullMethodName    = "/auth.AuthService/GetUserAuthorizedResFields"
	AuthService_GetUserAuthorizedResIdsSQL_FullMethodName    = "/auth.AuthService/GetUserAuthorizedResIdsSQL"
	AuthService_GetUserAuthorizedResFieldsSQL_FullMethodName = "/auth.AuthService/GetUserAuthorizedResFieldsSQL"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Ping(ctx context.Context, in *common.EmptyReq, opts ...grpc.CallOption) (*PingRes, error)
	// 校验用户权限
	CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionRes, error)
	// 查询用户已授权的资源的ID
	GetUserAuthorizedResIds(ctx context.Context, in *GetUserAuthorizedResIdsReq, opts ...grpc.CallOption) (*GetUserAuthorizedResIdsRes, error)
	// 查询用户已授权的资源的字段值
	GetUserAuthorizedResFields(ctx context.Context, in *GetUserAuthorizedResFieldsReq, opts ...grpc.CallOption) (*GetUserAuthorizedResFieldsRes, error)
	// 获取 查询用户已授权的资源的ID 的SQL
	GetUserAuthorizedResIdsSQL(ctx context.Context, in *GetUserAuthorizedResIdsSQLReq, opts ...grpc.CallOption) (*GetUserAuthorizedResIdsSQLRes, error)
	// 获取 查询用户已授权的资源的字段值 的SQL
	GetUserAuthorizedResFieldsSQL(ctx context.Context, in *GetUserAuthorizedResFieldsSQLReq, opts ...grpc.CallOption) (*GetUserAuthorizedResFieldsSQLRes, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Ping(ctx context.Context, in *common.EmptyReq, opts ...grpc.CallOption) (*PingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingRes)
	err := c.cc.Invoke(ctx, AuthService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionRes)
	err := c.cc.Invoke(ctx, AuthService_CheckPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserAuthorizedResIds(ctx context.Context, in *GetUserAuthorizedResIdsReq, opts ...grpc.CallOption) (*GetUserAuthorizedResIdsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAuthorizedResIdsRes)
	err := c.cc.Invoke(ctx, AuthService_GetUserAuthorizedResIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserAuthorizedResFields(ctx context.Context, in *GetUserAuthorizedResFieldsReq, opts ...grpc.CallOption) (*GetUserAuthorizedResFieldsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAuthorizedResFieldsRes)
	err := c.cc.Invoke(ctx, AuthService_GetUserAuthorizedResFields_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserAuthorizedResIdsSQL(ctx context.Context, in *GetUserAuthorizedResIdsSQLReq, opts ...grpc.CallOption) (*GetUserAuthorizedResIdsSQLRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAuthorizedResIdsSQLRes)
	err := c.cc.Invoke(ctx, AuthService_GetUserAuthorizedResIdsSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserAuthorizedResFieldsSQL(ctx context.Context, in *GetUserAuthorizedResFieldsSQLReq, opts ...grpc.CallOption) (*GetUserAuthorizedResFieldsSQLRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAuthorizedResFieldsSQLRes)
	err := c.cc.Invoke(ctx, AuthService_GetUserAuthorizedResFieldsSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	Ping(context.Context, *common.EmptyReq) (*PingRes, error)
	// 校验用户权限
	CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionRes, error)
	// 查询用户已授权的资源的ID
	GetUserAuthorizedResIds(context.Context, *GetUserAuthorizedResIdsReq) (*GetUserAuthorizedResIdsRes, error)
	// 查询用户已授权的资源的字段值
	GetUserAuthorizedResFields(context.Context, *GetUserAuthorizedResFieldsReq) (*GetUserAuthorizedResFieldsRes, error)
	// 获取 查询用户已授权的资源的ID 的SQL
	GetUserAuthorizedResIdsSQL(context.Context, *GetUserAuthorizedResIdsSQLReq) (*GetUserAuthorizedResIdsSQLRes, error)
	// 获取 查询用户已授权的资源的字段值 的SQL
	GetUserAuthorizedResFieldsSQL(context.Context, *GetUserAuthorizedResFieldsSQLReq) (*GetUserAuthorizedResFieldsSQLRes, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Ping(context.Context, *common.EmptyReq) (*PingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAuthServiceServer) CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPermission not implemented")
}
func (UnimplementedAuthServiceServer) GetUserAuthorizedResIds(context.Context, *GetUserAuthorizedResIdsReq) (*GetUserAuthorizedResIdsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAuthorizedResIds not implemented")
}
func (UnimplementedAuthServiceServer) GetUserAuthorizedResFields(context.Context, *GetUserAuthorizedResFieldsReq) (*GetUserAuthorizedResFieldsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAuthorizedResFields not implemented")
}
func (UnimplementedAuthServiceServer) GetUserAuthorizedResIdsSQL(context.Context, *GetUserAuthorizedResIdsSQLReq) (*GetUserAuthorizedResIdsSQLRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAuthorizedResIdsSQL not implemented")
}
func (UnimplementedAuthServiceServer) GetUserAuthorizedResFieldsSQL(context.Context, *GetUserAuthorizedResFieldsSQLReq) (*GetUserAuthorizedResFieldsSQLRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAuthorizedResFieldsSQL not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Ping(ctx, req.(*common.EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CheckPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckPermission(ctx, req.(*CheckPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserAuthorizedResIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAuthorizedResIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserAuthorizedResIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserAuthorizedResIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserAuthorizedResIds(ctx, req.(*GetUserAuthorizedResIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserAuthorizedResFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAuthorizedResFieldsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserAuthorizedResFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserAuthorizedResFields_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserAuthorizedResFields(ctx, req.(*GetUserAuthorizedResFieldsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserAuthorizedResIdsSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAuthorizedResIdsSQLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserAuthorizedResIdsSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserAuthorizedResIdsSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserAuthorizedResIdsSQL(ctx, req.(*GetUserAuthorizedResIdsSQLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserAuthorizedResFieldsSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAuthorizedResFieldsSQLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserAuthorizedResFieldsSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserAuthorizedResFieldsSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserAuthorizedResFieldsSQL(ctx, req.(*GetUserAuthorizedResFieldsSQLReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AuthService_Ping_Handler,
		},
		{
			MethodName: "CheckPermission",
			Handler:    _AuthService_CheckPermission_Handler,
		},
		{
			MethodName: "GetUserAuthorizedResIds",
			Handler:    _AuthService_GetUserAuthorizedResIds_Handler,
		},
		{
			MethodName: "GetUserAuthorizedResFields",
			Handler:    _AuthService_GetUserAuthorizedResFields_Handler,
		},
		{
			MethodName: "GetUserAuthorizedResIdsSQL",
			Handler:    _AuthService_GetUserAuthorizedResIdsSQL_Handler,
		},
		{
			MethodName: "GetUserAuthorizedResFieldsSQL",
			Handler:    _AuthService_GetUserAuthorizedResFieldsSQL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/apps/auth/proto/auth.proto",
}
